import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import brandsRouter from "./brands";
import productsRouter from "./products";
import cashSessionsRouter from "./cashSessions";
import repairsRouter from "./repairs";
import repairPartsRouter from "./repairParts";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import authRouter from "./auth";
import paymentMethodsRouter from "./paymentMethods";
import warehousesRouter from "./warehouses";
import installmentPlansRouter from "./installmentPlans";
import installmentSalesRouter from "./installmentSales";
import customersRouter from "../modules/customers/routes/customers";
import suppliersRouter from "../modules/suppliers/routes/suppliers";
import salesRouter from "../modules/sales/routes/sales";
import purchasesRouter from "../modules/purchases/routes/purchases";
import expensesRouter from "../modules/expenses/routes/expenses";
import vouchersRouter from "../modules/vouchers/routes/vouchers";
import accountingRouter from "../modules/accounting";
import barcodeSearchRouter from "./barcodeSearch";
import { requireAuth } from "../lib/auth-middleware";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/categories", requireAuth, categoriesRouter);
router.use("/brands", requireAuth, brandsRouter);
router.use("/products", requireAuth, productsRouter);
router.use("/customers", requireAuth, customersRouter);
router.use("/cash-sessions", requireAuth, cashSessionsRouter);
router.use("/sales", requireAuth, salesRouter);
router.use("/repairs", requireAuth, repairsRouter);
router.use("/repair-parts", requireAuth, repairPartsRouter);
router.use("/expenses", requireAuth, expensesRouter);
router.use("/reports", requireAuth, reportsRouter);
router.use("/settings", requireAuth, settingsRouter);
router.use("/payment-methods", requireAuth, paymentMethodsRouter);
router.use("/suppliers", requireAuth, suppliersRouter);
router.use("/vouchers", requireAuth, vouchersRouter);
router.use("/warehouses", requireAuth, warehousesRouter);
router.use("/installment-plans", requireAuth, installmentPlansRouter);
router.use("/installment-sales", requireAuth, installmentSalesRouter);
router.use("/purchases", requireAuth, purchasesRouter);
router.use("/accounting", requireAuth, accountingRouter);
router.use("/barcode-search", requireAuth, barcodeSearchRouter);

export default router;
